### ISSUE TITLE
Updating from an older version causes problems with assing a json object to a struct

### ISSUE THREAD

**Issue by JimmySnails** [nlohmann/json#1630]
Hi,

I've updated the json library from 3.1.2 to 3.6.1. Mostly because after upgrading to C++17, clang-7 failed to build and i found an issue which seemed to be fixed in the newer version.

`cannot convert from 'const json' to 'SettingsData'`
`cannot convert from 'initializer list' to 'json'`

And i get this error directly from the json library:
```
Error (active)	E0493	no instance of overloaded function "std::swap" matches the specified type	Cytopia	C:\Projekte\Cytopia\Cytopia\src\ThirdParty\json.hxx	17771	
```

Now, my build fails when writing a json object, read from a file (from_json) back to a struct variable:

```
  std::string settingsFileName = SDL_GetBasePath();
  settingsFileName.append(SETTINGS_FILE_NAME);
  std::ifstream i(settingsFileName);

  if (i.fail())
  {
    LOG(LOG_ERROR) << "File " << SETTINGS_FILE_NAME << " does not exist! Cannot load settings from INI File!";
    // Application should quit here, without settings from the ini file we can't continue
    return;
  }

  // check if json file can be parsed
  const json _settingsJSONObject = json::parse(i, nullptr, false);
  if (_settingsJSONObject.is_discarded())
  {
    LOG(LOG_ERROR) << "Error parsing JSON File " << SETTINGS_FILE_NAME;
  }
  SettingsData data = _settingsJSONObject;
```

and the from_json function:

```
// JSON deserializer for Settings struct
void from_json(const json &j, SettingsData &s)
{
  s.screenWidth = j["Graphics"]["Resolution"].value("Screen_Width", 800);
  s.screenHeight = j["Graphics"]["Resolution"].value("Screen_Height", 600);
  s.vSync = j["Graphics"].value("VSYNC", false);
  s.fullScreen = j["Graphics"].value("FullScreen", false);
  s.fullScreenMode = j["Graphics"].value("FullScreenMode", 0);
  s.mapSize = j["Game"].value("MapSize", 64);
  s.maxElevationHeight = j["Game"].value("MaxElevationHeight", 32);
  s.uiDataJSONFile = j["ConfigFiles"].value("UIDataJSONFile", "resources/data/TileData.json");
  s.tileDataJSONFile = j["ConfigFiles"].value("TileDataJSONFile", "resources/data/UIData.json");
  s.uiLayoutJSONFile = j["ConfigFiles"].value("UILayoutJSONFile", "resources/data/UILayout.json");
  s.playMusic = j["Audio"].value("PlayMusic", true);
  s.playSoundEffects = j["Audio"].value("PlaySoundEffects", false);
  s.audioChannels = j["Audio"].value("AudioChannels", 2);
  s.musicVolume = j["Audio"].value("MusicVolume", static_cast<uint8_t>(50));
  s.soundEffectsVolume = j["Audio"].value("SoundEffectsVolume", static_cast<uint8_t>(100));
  s.buildMenuPosition = j["User Interface"].value("BuildMenu Position", "BOTTOM");
}
```

I haven't commited the new json library because it fails to compile, but if you want to take a look at the code, it's this specific branch:
https://github.com/JimmySnails/Cytopia/tree/uiImprovements
and here's one of the files i use it:
https://github.com/JimmySnails/Cytopia/blob/uiImprovements/src/engine/basics/Settings.cxx

I use it the same way throughout my project and all fail the same way..

Can you help me out here, please?

**Comment by JimmySnails** [comment]
I just tried other versions, and it still works with 3.2.0 but fails the same way with 3.3.0 and above

**Comment by JimmySnails** [comment]
At least 3.3.0 fixed the clang error, so i'm good :)

**Comment by nickaein** [comment]
By concatenating the codes from `Settings.hpp`, `Settings.cxx` and the JSON library itself into a single file, plus some minor tweaks (e.g. removing references to Constants.hpp), I was able to get it working on Clang-7: https://godbolt.org/z/DpqLtW

The issue seems to be the order of declaring `from_json` and `to_json` method. It got fixed by defining them before `readFile` and `writeFile` implementation.

**Comment by JimmySnails** [comment]
Thank you! This really helped me a lot! I move the `from_json` and `to_json` functions into a seperate header file and now this works.

Still get an error at TerrainGenerator.cxx at

```
  // check if json file can be parsed
  json biomeDataJsonObject = json::parse(i, nullptr, false);
  if (biomeDataJsonObject.is_discarded())
  {
    LOG(LOG_ERROR) << "Error parsing JSON File " << TERRAINGEN_DATA_FILE_NAME;
  }
  // parse biome objects
  for (const auto &it : biomeDataJsonObject.items())
  {
    biomeInformation[it.key()] = it.value();
  }
```

```
Error	C2679	 binary '=': no operator found which takes a right-hand operand of type 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' (or there is no acceptable conversion)	Cytopia	C:\Projekte\Cytopia\Cytopia\src\engine\map\TerrainGenerator.cxx	168	
```

Going to take a look at that tomorrow.

If i'm stuck, should i open a new ticket or use this one?

**Comment by nickaein** [comment]
You're welcome!

Have you implemented `from_json` (and probably `to_json`) for `BiomeData` type too? For testing, you can declare these two functions without any implementation detail to see if that fixes the compile errors.

> If i'm stuck, should i open a new ticket or use this one?

The current problem seems to be similar to the first one, so I suppose you can continue to post on this issue. Whenever you felt the scope of your issue is changing, feel free to open a separate issue.

As a side note, great job on [Cytopia](https://github.com/JimmySnails/Cytopia)! Looking forward to see its first release :-)

**Comment by JimmySnails** [comment]
Thank you, i overlook that and also moved it to a seperate hxx. Anyway, the code is much cleaner now :)

Now i still have to figure out how to use a newer version of libstdc++ with clang on travis... *eyes rolling*

Really cool you like my project! :) We're on itch.io too, Keep an eye on it, we're making a lot of progress lately now we have more devs.
